language: python
# command to install dependencies
install:
  - pip install .
  - pip install -r requirements.txt
  - pip install pytest-cov

# command to run tests
script:
  - pytest
  - pytest --cov=./

after_success:
- codecov
